-- ============================================================
-- Oracle Database Initialization for Debezium CDC
-- ============================================================
-- This script runs as SYS user on XE (CDB$ROOT) instance
-- All CDC setup in ONE place!

-- ============================================================
-- Step 1: Enable Supplemental Logging at CDB Level
-- ============================================================

-- Enable minimal supplemental logging at CDB level
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;

-- Enable supplemental logging for primary keys at CDB level
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;

-- ============================================================
-- Step 2: Create Debezium CDC User (for Oracle Source Connector)
-- ============================================================

-- Create Debezium user (C##DBZUSER for CDB - uppercase required)
CREATE USER C##DBZUSER IDENTIFIED BY ${ORACLE_CDC_PASSWORD}
  DEFAULT TABLESPACE users
  QUOTA UNLIMITED ON users;

-- Grant necessary privileges for LogMiner CDC (CONTAINER=ALL for access to all PDBs)
GRANT CREATE SESSION TO C##DBZUSER CONTAINER=ALL;
GRANT SET CONTAINER TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$DATABASE TO C##DBZUSER CONTAINER=ALL;
GRANT FLASHBACK ANY TABLE TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ANY TABLE TO C##DBZUSER CONTAINER=ALL;
GRANT LOCK ANY TABLE TO C##DBZUSER CONTAINER=ALL;
GRANT CREATE TABLE TO C##DBZUSER CONTAINER=ALL;
GRANT ALTER ANY TABLE TO C##DBZUSER CONTAINER=ALL;
GRANT DROP ANY TABLE TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT_CATALOG_ROLE TO C##DBZUSER CONTAINER=ALL;
GRANT EXECUTE_CATALOG_ROLE TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ANY TRANSACTION TO C##DBZUSER CONTAINER=ALL;
GRANT LOGMINING TO C##DBZUSER CONTAINER=ALL;

-- Grant access to LogMiner packages
GRANT EXECUTE ON DBMS_LOGMNR TO C##DBZUSER CONTAINER=ALL;
GRANT EXECUTE ON DBMS_LOGMNR_D TO C##DBZUSER CONTAINER=ALL;

-- Grant SELECT on DBA views for CDC
GRANT SELECT ON V_$LOG TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$LOG_HISTORY TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_LOGS TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_CONTENTS TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_PARAMETERS TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$LOGFILE TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVED_LOG TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVE_DEST_STATUS TO C##DBZUSER CONTAINER=ALL;

-- ============================================================
-- Now switch to PDB and create application tables
-- ============================================================

-- Connect to pluggable database where APP_USER was created
ALTER SESSION SET CONTAINER = ${ORACLE_DATABASE};

-- Switch to app user schema (auto-uppercase by Oracle)
ALTER SESSION SET CURRENT_SCHEMA = ${ORACLE_APP_USER};

-- ============================================================
-- Table: USERS
-- ============================================================
CREATE TABLE USERS (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USERNAME VARCHAR2(100) NOT NULL UNIQUE,
    EMAIL VARCHAR2(255) NOT NULL UNIQUE,
    FULL_NAME VARCHAR2(255),
    STATUS VARCHAR2(20) DEFAULT 'active',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- Table: USER_ACTIVITIES
-- ============================================================
CREATE TABLE USER_ACTIVITIES (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    ACTIVITY_TYPE VARCHAR2(50) NOT NULL,
    DESCRIPTION CLOB,
    IP_ADDRESS VARCHAR2(45),
    USER_AGENT CLOB,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_USER_ACTIVITIES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- Create indexes for better query performance
-- Note: USERNAME and EMAIL already have indexes from UNIQUE constraints
CREATE INDEX IDX_USERS_STATUS ON USERS(STATUS);
CREATE INDEX IDX_USER_ACTIVITIES_USER_ID ON USER_ACTIVITIES(USER_ID);
CREATE INDEX IDX_USER_ACTIVITIES_TYPE ON USER_ACTIVITIES(ACTIVITY_TYPE);
CREATE INDEX IDX_USER_ACTIVITIES_CREATED_AT ON USER_ACTIVITIES(CREATED_AT);

-- ============================================================
-- Enable Supplemental Logging at Table Level (in PDB)
-- ============================================================

-- Enable supplemental logging at table level
ALTER TABLE USERS ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE USER_ACTIVITIES ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

-- ============================================================
-- Step 5: Verification (Optional - for debugging)
-- ============================================================

-- Switch back to CDB$ROOT to verify CDC user
ALTER SESSION SET CONTAINER = CDB$ROOT;

-- Show CDC user status
SELECT username, account_status, created FROM dba_users WHERE username = 'C##DBZUSER';

-- Show supplemental logging status
SELECT supplemental_log_data_min, supplemental_log_data_pk FROM v$database;

COMMIT;
